### ISSUE TITLE
Can you tell me what the problem is?

### ISSUE THREAD

**Issue by jiwonwanny** [danielcalencar/ma-szz#1]
Hello.
Thank you so much for sharing useful source code.

I ran the 'MA-SZZ' algorithm.
But I get no results in the 'bugintroducingcode' table.

And I got the result like the attached files.
Could you please let me know what part I'm doing wrong?
![problem](https://user-images.githubusercontent.com/38281306/153340777-5f376a1a-c4c4-42e0-9cdc-61b2a9261fb1.JPG)

**Comment by danielcalencar** [comment]
Dear @jiwonwanny ,

Thanks for contacting. Have you checked if in your linkedissuessvn table your issues have the "Bug" value in the "issuetype" column? Note that you are not getting any issues from the database so that SZZ can work on them.

Also, if you check my repository called "raszzprime" you can also run both RA-SZZ and MA-SZZ from that code.

Let me know how you go about it,

Cheers,
Dan

**Comment by jiwonwanny** [comment]
Thank you very much for your kind reply.
I was missing the value of the "issuetype" column as you said.
Thanks to you, I was able to solve the problem.

sincerely,
Jiwon
